version: 2.1
orbs:
  datadog: datadog/datadog-static-analyzer-circleci-orb@1.0.4

jobs:
  test:
    docker:
      - image: pbxx/go-docker-base
    working_directory: /go/src/github.com/promoboxx/go-glitch
    steps:
      - checkout

      - run:
          name: go vet
          command: go vet -mod vendor ./fb/...
      - run:
          name: gofmt
          command: test -z "$(gofmt -s -l fb)"
      - run:
          name: go test
          command: go test -race -run Unit ./...

      - store_test_results:
          path: testresults
  run-static-analysis-job:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - datadog/analyze:
          service: "go-glitch"
          env: "ci"
          site: datadoghq.com
          cpu_count: 2

workflows:
  version: 2 
  test:
    jobs:
      - test
      - run-static-analysis-job:
          context:
            - datadog

